name: lemmy_api_client
description: Dart client for the Lemmy API. Provides an easy interface and statically typed responses.
version: 0.1.0
repository: https://github.com/thunder-app/lemmy_api_client

environment:
  sdk: ^3.7.0

dependencies:
  json_annotation: ^4.9.0
  http: ^1.3.0
  freezed_annotation: ^2.4.4

dev_dependencies:
  build_runner: ^2.4.15
  freezed: 2.5.8
  json_serializable: 6.9.4
  lints: ^5.1.1
  test: ^1.25.15