name: lemmy_dart_client
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.6.2

dependencies:
  dio: ^5.8.0+1
  lemmy_dart_api_0_19_6:
    path: packages/lemmy_dart_api_0_19_6
  lemmy_dart_api_1_0_0:
    path: packages/lemmy_dart_api_1_0_0
  openapi_generator_annotations: ^6.1.0

dev_dependencies:
  build_runner: ^2.4.14
  lints: ^5.0.0
  openapi_generator: ^6.1.0
  test: ^1.24.0
